oc:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: ${TOKEN_SECRET}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: back
logging:
  level:
    org:
      hibernate:
        type: info
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: info
    com:
      openclassrooms: info